version: '3'

services:
  web:
    build: .
    ports:
      - "5069:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - X-AUTH-TOKEN=${X_AUTH_TOKEN}